on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:

  release-please:
    runs-on: ubuntu-latest

    steps:
      - uses: googleapis/release-please-action@v4
        id: release
        with:
          release-type: php

      - name: Extract version
        id: release-variables
        if: ${{ steps.release.outputs.pr }}
        run: |
          VERSION=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.title' | grep -oP '(?<=release )\d+\.\d+\.\d+')
          BASE_BRANCH_NAME=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.baseBranchName')
          HEAD_BRANCH_NAME=$(echo '${{ steps.release.outputs.pr }}' | jq -r '.headBranchName')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "baseBranchName=$BASE_BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "headBranchName=$HEAD_BRANCH_NAME" >> $GITHUB_OUTPUT
          echo "version=$VERSION"
          echo "baseBranchName=$BASE_BRANCH_NAME"
          echo "headBranchName=$HEAD_BRANCH_NAME"

      - name: Checkout repository
        if: ${{ steps.release.outputs.pr }}
        uses: actions/checkout@v4
        with:
          ref: ${{ steps.release-variables.outputs.headBranchName }}

      - name: Set up PHP
        if: ${{ steps.release.outputs.pr }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'

      - name: Install Composer dependencies
        if: ${{ steps.release.outputs.pr }}
        run: composer install

      - name: Build project
        if: ${{ steps.release.outputs.pr }}
        run: php poortman app:build -n --build-version=${{ steps.release-variables.outputs.version }}

      - name: Commit and push changes
        if: ${{ steps.release.outputs.pr }}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: 'chore: build v${{ steps.release-variables.outputs.version }}'
          branch: ${{ steps.release-variables.outputs.headBranchName }}
          file_pattern: 'builds/*'

      - name: Upload Release Artifact
        if: ${{ steps.release.outputs.release_created }}
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ steps.release.outputs.tag_name }} ./builds/poortman